Repository smu06030/bangkok-style, pull requests merged in 2024-08, with the labels that each got.

#8 Feature/posts
  pull_request_template.md
  src/assets/images/dummy.jpg
  src/components/Layout/Posts.jsx
  src/main.jsx
  src/pages/public/Home.jsx
  src/store/Context/EntireProvider.jsx
  src/store/reducers/postsReducer.js
Labels: 기능개발, 문서수정

#9 feat: useFetchPosts 커스텀 훅 개발
  src/components/Layout/Posts.jsx
  src/hooks/useFetchPosts.js
Labels: 구조 변경, 리펙토링

#10 add:로그인 시 유저 정보를 저장하는 로직 추가
  src/components/Layout/ProtectedHeader.jsx
  src/constant/regularExpression.js
  src/constant/signInputsElements.js
  src/hooks/useSignInHandler.js
  src/hooks/useSignUpHandler.js
  src/pages/public/Home.jsx
  src/pages/public/SignIn.jsx
  src/pages/public/SignUp.jsx
  src/store/Context/EntireProvider.jsx
  src/store/reducers/signInReducer.js
Labels: 기능개발, 긴급

#11 feat: PostCard UI 분리
  src/assets/images/Like.jsx
  src/assets/images/LikeActive.jsx
  src/components/Layout/PostCard.jsx
  src/components/Layout/Posts.jsx
Labels: 기능개발, 구조 변경, 리펙토링

#12 fix:유저정보 state명 변경, bugfix:로그아웃 에러 해결
  src/Test.jsx
  src/components/Layout/Layout.jsx
  src/constant/signInputsElements.js
  src/hooks/useSignInHandler.js
  src/main.jsx
  src/pages/Like.jsx
  src/routes/ProtectedRoute.jsx
  src/routes/PublicRoute.jsx
  src/store/Context/EntireProvider.jsx
Labels: 버그, 기능개발

#13 Feature/posts
  src/assets/images/Like.jsx
  src/assets/images/Likes.jsx
  src/assets/images/Loading.jsx
  src/components/Layout/PostCard.jsx
  src/components/Layout/Posts.jsx
  src/components/Layout/ProtectedHeader.jsx
  src/hooks/useFetchPosts.js
  src/utils/updateLikeStatus.js
Labels: 버그, 기능개발, 리펙토링

#14 move:context, onAuthStateChange App.jsx로 이동 style:로그인, 회원가입 페이지 스타일링
  src/App.css
  src/App.jsx
  src/Context/ContextProvider.jsx
  src/Context/EntireContext.jsx
  src/components/Layout/Layout.jsx
  src/components/SignInputs.jsx
  src/constant/regularExpression.js
  src/hooks/useFetchPosts.js
  src/hooks/useOnAuthStateChange.js
  src/hooks/useSignInHandler.js
  src/hooks/useSignUpHandler.js
  src/index.css
  src/main.jsx
  src/modules/postsReducer.js
  src/modules/signInReducer.js
  src/pages/Like.jsx
  src/pages/public/SignIn.jsx
  src/pages/public/SignUp.jsx
  src/routes/ProtectedRoute.jsx
  src/routes/PublicRoute.jsx
  src/store/Context/EntireProvider.jsx
  src/styles/GlobalStyle.jsx
  src/styles/SignStyles.js
Labels: 구조 변경, 리펙토링

#15 Feature/posts
  src/Context/ContextProvider.jsx
  src/components/Layout/Banner.jsx
  src/components/Layout/Layout.jsx
  src/components/Layout/PostCard.jsx
  src/components/Layout/Posts.jsx
  src/components/UI/Button.jsx
  src/constant/constants.js
  src/hooks/useFetchPosts.js
  src/hooks/useSignInHandler.js
  src/modules/postsReducer.js
  src/services/getAllDataService.js
  src/services/likeService.js
  src/styles/GlobalStyle.jsx
  src/utils/filteredDisplayedPostsData.js
  src/utils/formattedLikeData.js
  src/utils/updateLikeStatus.js
Labels: 기능개발, 구조 변경

#16 feat:input 정규표현식 추가
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.jsx
  src/components/Layout/Layout.jsx
  src/components/Layout/PrivateHeader.jsx
  src/components/SignInputs.jsx
  src/constant/regularExpression.js
  src/hooks/useOnAuthStateChange.js
  src/hooks/useSignInHandler.js
  src/hooks/useSignUpHandler.js
  src/pages/private/MyPage.jsx
  src/pages/public/PasswordRecovery.jsx
  src/pages/public/SignIn.jsx
  src/pages/public/SignUp.jsx
  src/routes/PrivateRoute.jsx
  src/routes/index.jsx
  src/styles/GlobalStyle.jsx
  src/styles/SignStyles.js
  yarn.lock
Labels: 기능개발
